version: '4.12'

services:
  #MongoDB services
  mongo_db:
    container_name: db_container
    image: mongo:latest
    restart: always
    volumes:
      - mongo_db:/data/db

  #Node API
  api:
    build: .
    ports:
      - 4000:8080
    environment:
      PORT: 8080
      MONGODB_URI: mongodb://mongo_db:27017/users_db
      DB_NAME: users
      NAME: Jensenfy
    depends_on:
      - mongo_db

volumes:
  mongo_db: {}
