name: deplo-to-integration
on: push
jobs:
  any-job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: install
        run: npm i
      - name: integrationtest
        run: npm run integrationtest
